language: php

php:
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

branches:
  except:
    - gh-pages

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --dev --no-interaction --prefer-source

script:
  - phpunit -c phpunit.xml.dist --coverage-clover phpunit-coverage-clover.xml

after_script:
  - php vendor/bin/coveralls

after_success:
  - composer require --no-update composer/composer:*@dev
  - composer require kzykhys/markbench:*@dev
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=blank
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=default
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=github-sample
