language: php

php:
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

branches:
  except:
    - gh-pages

notifications:
  slack:
    secure: YXEgHrSuEjhLunbMr8dyXZZ5AaAOK9Wc75Rl/HcxCFM4iUoPJj6S7E3EtgW58bYaF1M9xNYwOP5FKD1alMko94xTYdsrf0t3AkpDqll+bEY+EOiixRavRCQUqins9pFK/WK4DmfH28aFnEZBc2dak1pU0dmdJ0Ywzk8rJ8twLNI=

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --dev --no-interaction --prefer-source

script:
  - phpunit -c phpunit.xml.dist --coverage-clover phpunit-coverage-clover.xml

after_script:
  - vendor/scrutinizer/ocular/bin/ocular code-coverage:upload --format=clover phpunit-coverage-clover.xml